CREATE TABLE [dbo].[APP](
	[KDAPP] [nchar](10) NOT NULL,
	[IDAPP] [nchar](36) NULL,
	[NMAPP] [nvarchar](50) NULL,
	[URL] [nvarchar](100) NULL,
	[STATUS] [int] NULL,
	[KDLEVEL] [smallint] NULL,
	[TYPE] [nchar](1) NULL,
 CONSTRAINT [PK_APP] PRIMARY KEY CLUSTERED 
(
	[KDAPP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]